### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by BehindTheMath** [dmfilipenko/timezones.json#12]
The following timezones are missing the `utc` property:

[`Mid-Atlantic Standard Time`](https://github.com/dmfilipenko/timezones.json/blob/53a47e0dd973729d09b4817d7c012673e4e7f164/timezones.json#440-L446)

[`E. Europe Standard Time`](https://github.com/dmfilipenko/timezones.json/blob/53a47e0dd973729d09b4817d7c012673e4e7f164/timezones.json#678-L684)

**Comment by dmfilipenko** [comment]
@BehindTheMath Feel free to make pull request
