### ISSUE TITLE
Duplicate timezones

### ISSUE THREAD

**Issue by GaikwadPratik** [dmfilipenko/timezones.json#28]
Some of the places in the `json` file are placed in different timezones. Most of them are European places. One such instance is:

```
{
    "value": "Greenwich Mean Time",
    "abbr": "GMT",
    "offset": 0,
    "isdst": false,
    "text": "(UTC) Edinburgh, London",
    "utc": [
      "Europe/Isle_of_Man",
      "Europe/Guernsey",
      "Europe/Jersey",
      "Europe/London"
    ]
  },
  {
    "value": "British Summer Time",
    "abbr": "BST",
    "offset": 1,
    "isdst": true,
    "text": "(UTC+01:00) Edinburgh, London",
    "utc": [
      "Europe/Isle_of_Man",
      "Europe/Guernsey",
      "Europe/Jersey",
      "Europe/London"
    ]
  }
```

Is this intentional? Because that is breaking in UI, when I am trying to map to dropdown.

**Comment by dmfilipenko** [comment]
@GaikwadPratik will take a look

**Comment by dmfilipenko** [comment]
@GaikwadPratik Seems it's valid according to https://www.timeanddate.com/time/zones/gmt
https://www.timeanddate.com/time/zones/bst

**Comment by GaikwadPratik** [comment]
oh boy, _**European countries/territories using BST in the summer and GMT in the winter**_

This means that the consumer application will have to keep track of _summer_ and _winter_ in those areas. People are certainly not making it easier to use different timezones are they? Also need to find more such duplicates areas and find more information about them and handle those or use _moment_ along with this library. 

Thank you for helping here!
