### ISSUE TITLE
Data is incorrect (does not account for DST)

### ISSUE THREAD

**Issue by andsav** [dmfilipenko/timezones.json#32]
For example:

```
 "value": "Eastern Standard Time",
    "abbr": "EDT",
    "offset": -4,
    "isdst": true,
    "text": "(UTC-05:00) Eastern Time (US & Canada)",
```

The offset `-4` is correct for daylight time, but the text displays `(UTC-5:00)`. Furthermore, EDT stands for Eastern Daylight Time not Eastern Standard Time. I see there are a lot of mismatches between offset and what is displayed in the text, so I don't think the data is correct.

**Comment by martin-sweeny** [comment]
@dmfilipenko why did you close this lol
