### ISSUE TITLE
Timezone parameter does not change the output of the api

### ISSUE THREAD

**Issue by warebytes** [dmfilipenko/timezones.json#45]
I have noticed that whatever time zone I place in the request parameters, the time remains the same (local time in Morocco).

Example: https://www.prayertimes.mahmoud.ma/api/80/today?timezone=Pacific/Midway
Test date: Sat, 18. Sept 2021 - 12:02 pm
Result: {"fajr":"05:47","sunrise":"07:13","dohr":"13:30","asr":"16:54","maghreb":"19:37","ichaa":"20:51"}

Any ideas where the issue resides?

**Comment by dmfilipenko** [comment]
I'm not related to this API. Dont know a reason
